### ISSUE TITLE
No such file or directory: you-get

### ISSUE THREAD

**Issue by c02y** [Vayn/acmpv#2]
![64-14_13dead](https://cloud.githubusercontent.com/assets/2135996/19617967/141f9274-9804-11e6-97d6-c7a46779154d.png)
Excuse me?

FYI:
Fedora 24 64-bit
Python3 v3.5.2

**Comment by vayn** [comment]
Hi, acmpv has been updated. Could you reinstall it?

**Comment by c02y** [comment]
Exact the same error message after

```
git pull origin master
```

I didn't install the acmpv, just execute it from the local directory like the command line in the picture.

**Comment by vayn** [comment]
I can't reproduce the bug on my computer. Please try to execute `you-get` script of acmpv with the absolute  path in the screenshot.

**Comment by c02y** [comment]
You shouldn't use 

```
#!/usr/local/opt/python3/bin/python3.5
```

in `src/acmpv/you-get` file, that is the path in your OS (that file is not existed in mine), mine is `/usr/bin/python3.5`, changing it will work, but...

There will be errors when opening links.
1. When opening acfun links such as (I did not test all links just random one and the one in your README.md file which is in the picture I posted)
   
   ```
   ./acmpv http://www.acfun.tv/v/ac3196934
   ./acmpv http://www.acfun.tv/v/ac3171529
   ```
   
   there is a same error line saying 
   
   ```
   libFreeOCL.so: cannot open shared object file: No such file or directory
   ```
   
   in the command line output, but videos will be opened using mpv and it works fine.
2. When opening bilibili links such as (I just tested two random links, but printed both the same error messages)
   
   ```
   ./acmpv http://www.bilibili.com/video/av6722187/
   ./acmpv http://www.bilibili.com/video/av6773155/
   ```
   
   there will be errors saying
   
   ```
   libFreeOCL.so: cannot open shared object file: No such file or directory
   libFreeOCL.so: cannot open shared object file: No such file or directory
   INFO: Loading video info...
   libFreeOCL.so: cannot open shared object file: No such file or directory
   ERROR: Error message: overspeed
   ERROR: Can not get 'cid' from http://www.bilibili.com/video/avxxxxxx/
   ```
   
   and the videos won't be opened, the command line will just print error messages and exit.

I already got freeocl package installed in my Feora24 and libFreeOCL.so is not existed, google gives nothing useful.

**Comment by vayn** [comment]
1. I guess there is something wrong between libFreeOCL and mpv. First of all, you could try to link the lib.so to the system lib folder manually. Second, you can use `strace` to trace the execution.
2. Bilibili just banned our API underneath and I fixed it already.

**Comment by c02y** [comment]
The libFreeOCL.so file is not existed in my OS. 

Anyway, the acfun and bilibili videos can be played now. Thanks.

I'm wondering whether the feature that you can toggle the `danmu` when watching videos is included or in the TODO list.

**Comment by vayn** [comment]
You could hide or show subtitle/danmaku in mpv directly - just press "V" on keyboard
