### ISSUE TITLE
期待能够支持熊猫斗鱼的弹幕

### ISSUE THREAD

**Issue by ddqp** [Vayn/acmpv#3]
一直在用楼主的acmpv，A站很好用。

斗鱼熊猫没有弹幕，有些乏味，弹幕更有意思。

不知道可否支持一下。

**Comment by vayn** [comment]
熊猫斗鱼的弹幕和A站实现方式不一样，我抽空看看能不能支持:D

**Comment by ddqp** [comment]
好的，楼主！

这里面有全套实现方法，只是不能将弹幕加载到mpv上
https://github.com/littlecodersh/danmu

**Comment by vayn** [comment]
难点不在获取弹幕，而是如何实时在播放器里加载弹幕

**Comment by ddqp** [comment]
嗯，的确！
