### ISSUE TITLE
ACFUN无法播放了

### ISSUE THREAD

**Issue by ddqp** [Vayn/acmpv#4]
似乎是通病,you-get 也不行了

**Comment by vayn** [comment]
一会儿我升级到新版

**Comment by ddqp** [comment]
收到，谢谢，另外请教一个关于AppleScript问题：

之前都还是好好的,升级到 10.12.4 Beta 就出错了,错在 "URL of front document" 中的 URL 这个变量. 


on run {theURL, parameters}

-- Copies URL of the current tab to the clipboard
-- Requires Alfred PowerPack
tell application "Safari"
	set theURL to URL of front document
	set the clipboard to theURL as string
end tell

****set input02 to (theURL as text)****  
do shell script ("/usr/local/bin/you-get -p /usr/local/bin/mpv '" & input02 & "'")

return theURL
end run

**Comment by MakeHui** [comment]
#5 @Vayn

**Comment by vayn** [comment]
Thanks @MakeHui !
